from __future__ import annotations

# Names of the files and directories `init` writes, relative to the
# repository root. Kept as constants so a rename is a diff in one place.
CONFIG_FILE = "codehood.toml"
README_FILE = "README.md"
CALENDAR_FILE = "calendar.md"
GITIGNORE_FILE = ".gitignore"
QUESTIONS_DIR = "questions"
EXAMS_DIR = "exams"
RESOURCES_DIR = "resources"
MACHINE_DIR = ".codehood"
GIT_DIR = ".git"

# The example question and exam. Flat filenames -- see the spec's
# "`questions/` is flat too" and "`exams/` is flat" sections -- and plain
# `.md`, so editors and forges treat the file as Markdown.
EXAMPLE_ID = "example"
EXAMPLE_QUESTION_FILE = f"{EXAMPLE_ID}.md"
EXAMPLE_EXAM_FILE = f"{EXAMPLE_ID}.md"


def render_gitignore() -> str:
    """
    Render the `.gitignore` `init` writes at the repository root.

    Holds `.codehood/` (machine state, see the spec's "`.codehood/` is
    machine state" section) plus the usual OS noise. Nothing else: this is
    a content repository, not a Python project.
    """
    return f"{MACHINE_DIR}/\n.DS_Store\nThumbs.db\n"


def render_readme(name: str) -> str:
    """
    Render the `README.md` `init` writes.

    The H1 is a local title only -- the server has no course name, just
    `Discipline.name`, shared across every edition and instructor, and a
    per-course file must not rename a shared row. `push` sends the
    paragraph under the H1 as the course's description and ignores the H1
    itself; see `dev/specs/to-do/push.md`, "The README's H1 is ignored".
    """
    return (
        f"# {name}\n"
        "\n"
        "Course description. Edit this paragraph -- it becomes the course's\n"
        "public description, shown to someone who has not enrolled.\n"
    )


def read_course_name(text: str) -> tuple[str, str] | None:
    """
    Parse a README's H1 and description.

    The H1 is the course name; everything after it, up to the next
    heading, is the description.

    Args:
        text: The README's full content.

    Returns:
        A `(name, description)` pair, or `None` if the first non-blank
        line is not an H1.

    Example:
        >>> read_course_name("# CS 101\\n\\nAn intro course.\\n")
        ('CS 101', 'An intro course.')
    """
    lines = text.splitlines()
    index = 0
    while index < len(lines) and not lines[index].strip():
        index += 1
    if index >= len(lines) or not lines[index].startswith("# "):
        return None
    name = lines[index][2:].strip()
    description_lines: list[str] = []
    for line in lines[index + 1 :]:
        if line.startswith("#"):
            break
        description_lines.append(line)
    description = "\n".join(description_lines).strip()
    return name, description


def render_calendar() -> str:
    """
    Render the `calendar.md` `init` writes.

    Format is provisional -- the calendar spec that settles it is still in
    `dev/specs/to-do/` -- so this is placeholder frontmatter an instructor
    is expected to replace with the term's real dates.
    """
    return (
        "---\n"
        "start: 2026-01-01\n"
        "end:   2026-06-01\n"
        "days:\n"
        "  - Mon 14:00 2h, Lecture\n"
        "holidays: []\n"
        "---\n"
        "\n"
        "# Schedule\n"
        "\n"
        "## Course overview\n"
        "\n"
        "What we will cover, how grading works.\n"
        "\n"
        "* Course presentation\n"
        "* Instructor contact\n"
        "* Office hours\n"
    )


def render_example_question() -> str:
    """
    Render `questions/example.md`.

    Real MDQ, not a placeholder: it parses and it would push. It sets
    neither `id` nor a filename that disagrees with one, so the filename
    stem (`example`) is its id by default.
    """
    return (
        "---\n"
        "title: Example question\n"
        "---\n"
        "\n"
        "What is 2 + 2?\n"
        "\n"
        "- [ ] 3\n"
        "- [*] 4\n"
        "- [ ] 5\n"
    )


def render_example_exam(discipline: str) -> str:
    """
    Render `exams/example.md`.

    Includes the example question by id (`example`, the question's
    filename stem), so the pair parses and the first `codehood push` has
    something real to do.

    Args:
        discipline: The course's discipline slug, written as the exam's
            `course` field.
    """
    return (
        "---\n"
        f"course: {discipline}\n"
        "meta:\n"
        "  codehood:\n"
        "    type: quiz\n"
        "    scheduled_at: 2026-01-01T09:00:00\n"
        "    duration_min: 60\n"
        "---\n"
        "\n"
        "# Example Exam\n"
        "\n"
        "Generated by `codehood init`. Replace it with a real exam, or\n"
        "delete this pair along with `questions/example.md`.\n"
        "\n"
        "---\n"
        f"include: {EXAMPLE_ID}\n"
        "---\n"
    )
