/**
 * Links the user-story catalogue in `docs/user-stories` to the tests in
 * `test/stories` and reports the coverage.
 *
 * Stories and tests are matched by the slug of the story title, which is the
 * only thing tying the two together.
 *
 * - no flag: write `docs/user-stories/coverage.md`
 * - `--check`: validate without writing, for CI
 * - `--missing`: list the stories no test names
 * - `--covered`: list the stories a test names
 * - `--stale`: list the tests that name no story
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

// `--missing | head` closes stdout early; that is a finished read, not a fault.
process.stdout.on("error", (error: NodeJS.ErrnoException) => {
	if (error.code !== "EPIPE") throw error;
});

const STORIES_DIR = "docs/user-stories";
const TESTS_DIR = "test/stories";
const REPORT = join(STORIES_DIR, "coverage.md");

type Status = "todo" | "implemented" | "web" | "cli";

interface Story {
	role: string;
	section: string;
	title: string;
	slug: string;
	status: Status;
}

interface TestRef {
	role: string;
	title: string;
	slug: string;
	file: string;
}

/**
 * ANSI colours, off when the output is piped or `NO_COLOR` is set, so the
 * listing flags stay greppable.
 */
const colour = process.stdout.isTTY && !process.env.NO_COLOR;

function paint(code: string, text: string): string {
	return colour ? `\x1b[${code}m${text}\x1b[0m` : text;
}

const bold = (t: string) => paint("1", t);
const dim = (t: string) => paint("2", t);
const red = (t: string) => paint("31", t);
const green = (t: string) => paint("32", t);
const yellow = (t: string) => paint("33", t);
const cyan = (t: string) => paint("36", t);

/** Green for a story that is built, yellow for half of one, dim for neither. */
function paintStatus(status: Status): string {
	const shade =
		status === "implemented" ? green : status === "todo" ? dim : yellow;
	return dim("[status: ") + shade(status) + dim("]");
}

function slugify(title: string): string {
	return title
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-|-$/g, "");
}

function parseStories(role: string, source: string): Story[] {
	const stories: Story[] = [];
	let section = "";

	for (const block of source.split(/^(?=## |### )/m)) {
		const heading = block.match(/^(#{2,3}) (.+)$/m);
		if (!heading) continue;

		if (heading[1] === "##") {
			// biome-ignore lint/style/noNonNullAssertion: `(.+)` is a mandatory capture group in a match that already succeeded (the `if (!heading) continue` above).
			section = heading[2]!.trim();
			continue;
		}

		// biome-ignore lint/style/noNonNullAssertion: same mandatory capture group as above.
		const title = heading[2]!.trim();
		const status = block.match(/^\s{4}status:\s*"?(\w+)"?\s*$/m)?.[1] ?? "todo";
		stories.push({
			role,
			section,
			title,
			slug: slugify(title),
			status: status as Status,
		});
	}

	return stories;
}

function parseTests(file: string, source: string): TestRef[] {
	const refs: TestRef[] = [];

	for (const match of source.matchAll(/\btest\(\s*"([^"]+)"/g)) {
		// biome-ignore lint/style/noNonNullAssertion: `([^"]+)` is a mandatory capture group in a match matchAll already produced.
		const name = match[1]!;
		const [, role, title] = name.match(/^(\w+):\s*(.+)$/) ?? [];
		if (!role || !title) continue;
		refs.push({ role, title, slug: slugify(title), file });
	}

	return refs;
}

function readStories(): Story[] {
	return readdirSync(STORIES_DIR)
		.filter((f) => f.endsWith(".md") && !/^(README|coverage)\.md$/.test(f))
		.flatMap((f) =>
			parseStories(
				basename(f, ".md"),
				readFileSync(join(STORIES_DIR, f), "utf8"),
			),
		);
}

function readTests(): TestRef[] {
	return readdirSync(TESTS_DIR)
		.filter((f) => f.endsWith(".test.ts"))
		.flatMap((f) => parseTests(f, readFileSync(join(TESTS_DIR, f), "utf8")));
}

/** The stories whose slug is claimed twice in the same document. */
function findCollisions(stories: Story[]): string[] {
	const collisions: string[] = [];
	const seen = new Map<string, string>();

	for (const story of stories) {
		const key = `${story.role}/${story.slug}`;
		const clash = seen.get(key);
		if (clash) {
			collisions.push(
				`${story.role}.md: "${story.title}" and "${clash}" share the slug "${story.slug}"`,
			);
		}
		seen.set(key, story.title);
	}

	return collisions;
}

/**
 * The tests that name no story, which is what a renamed or deleted story leaves
 * behind.
 */
function findStale(stories: Story[], tests: TestRef[]): TestRef[] {
	const slugs = new Set(stories.map((s) => `${s.role}/${s.slug}`));
	return tests.filter((t) => !slugs.has(`${t.role}/${t.slug}`));
}

function report(stories: Story[], tests: TestRef[]): string {
	const covered = new Set(tests.map((t) => `${t.role}/${t.slug}`));
	const lines = [
		"# Story coverage",
		"",
		`Generated by \`pnpm run stories\`. Do not edit.`,
		"",
	];

	for (const role of [...new Set(stories.map((s) => s.role))]) {
		const roleStories = stories.filter((s) => s.role === role);
		const hits = roleStories.filter((s) => covered.has(`${role}/${s.slug}`));
		lines.push(
			`## ${role}`,
			"",
			`${hits.length} of ${roleStories.length} stories have a test.`,
			"",
			"| Story | Status | Tested |",
			"| :--- | :--- | :--- |",
		);
		for (const story of roleStories) {
			const tested = covered.has(`${role}/${story.slug}`) ? "yes" : "";
			lines.push(`| ${story.title} | ${story.status} | ${tested} |`);
		}
		lines.push("");
	}

	return lines.join("\n");
}

function list(stories: Story[]): void {
	for (const story of stories) {
		console.log(
			`${cyan(`${story.role}:`)} ${story.title} ${paintStatus(story.status)}`,
		);
	}
}

const stories = readStories();
const tests = readTests();
const collisions = findCollisions(stories);
const stale = findStale(stories, tests);
const covered = new Set(
	tests.filter((t) => !stale.includes(t)).map((t) => `${t.role}/${t.slug}`),
);
const tested = stories.filter((s) => covered.has(`${s.role}/${s.slug}`));
const untested = stories.filter((s) => !covered.has(`${s.role}/${s.slug}`));

function listStale(stale: TestRef[]): void {
	for (const test of stale) {
		console.log(
			`${dim(test.file)} ${cyan(`${test.role}:`)} ${test.title} ${red("names no story")}`,
		);
	}
}

/**
 * Reports the problems and settles the exit code.
 *
 * Never calls `process.exit` on the listing paths: killing the process can drop
 * buffered stdout when it is a pipe, which is exactly how these flags are used.
 */
function main(): void {
	if (process.argv.includes("--missing")) {
		list(untested);
		return;
	}

	if (process.argv.includes("--covered")) {
		list(tested);
		return;
	}

	if (process.argv.includes("--stale")) {
		listStale(stale);
		return;
	}

	for (const collision of collisions) console.error(red(collision));
	for (const test of stale) {
		console.error(
			red(
				`${test.file}: test "${test.role}: ${test.title}" names no story in ${test.role}.md`,
			),
		);
	}

	if (process.argv.includes("--check")) {
		if (readFileSync(REPORT, "utf8") !== report(stories, tests)) {
			console.error(red(`${REPORT} is out of date, run \`pnpm run stories\``));
			process.exitCode = 1;
			return;
		}
	} else {
		writeFileSync(REPORT, report(stories, tests));
	}

	if (collisions.length + stale.length > 0) {
		process.exitCode = 1;
		return;
	}

	const built = stories.filter((s) => s.status === "implemented").length;
	console.log(
		`${bold(`${tested.length} of ${stories.length}`)} stories have a test, ${bold(`${built}`)} are implemented`,
	);
}

main();
