/**
 * AUTOGENERATED -- DO NOT EDIT BY HAND.
 *
 * Generated by `scripts/generate-question-models.ts` from
 * `public/mdq.schema.json`. Run `pnpm run question-models` to regenerate.
 */
import { z } from "zod";

/**
 * An open-ended question where the student writes a free-form answer, rather
 * than choosing among predefined options. Extends the common question-base
 * schema with an `input` field describing how the answer should be edited, and
 * an optional answer key.
 */
export const EssaySchema = z
	.object({
		/**
		 * Url-friendly identifier for the question. Used to reference the question
		 * from exams, results, and cross-links. When omitted, an id may be derived
		 * from the question's position or title.
		 */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/**
		 * A universally unique identifier (UUID) for the question. Used to reference
		 * the question from exams, results, and cross-links. When omitted, a UUID may
		 * be generated automatically. Must be a valid UUID,
		 * `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` where `M` is the version and `N` is
		 * the variant.
		 */
		uuid: z
			.string()
			.regex(
				/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
			)
			.optional(),
		/**
		 * Human readable title, e.g. shown in question listings, tables of contents,
		 * or instructor-facing question banks.
		 */
		title: z.string().min(1).optional(),
		/** The name of the author or authors. Just for reference. */
		author: z.string().min(1).optional(),
		/**
		 * The main command shown to the students (e.g. "Select all correct answers",
		 * "Write a program that..."). This is the sentence that tells the student what
		 * to do and is always shown to them.
		 */
		stem: z.string().min(1),
		/**
		 * One or more paragraphs of context shown before the stem. May contain
		 * Markdown markup.
		 */
		preamble: z.string().optional(),
		/**
		 * One or more paragraphs of text shown after the question body (e.g. after the
		 * list of choices). May contain Markdown markup.
		 */
		epilogue: z.string().optional(),
		/**
		 * Free-form text shown only to instructors, never to students. Used to explain
		 * the intent of the question, grading rationale, formatting decisions, etc.
		 */
		comment: z.string().optional(),
		/**
		 * The language the question is written in, as an IETF BCP 47 language tag. BCP
		 * 47 is too involved to express as a JSON Schema `pattern`, so well-formedness
		 * is left to the implementation -- see the `malformed-locale` check in
		 * mdq.linter.
		 */
		locale: z.string().optional(),
		/** Arbitrary set of strings associated with the question. */
		tags: z.array(z.string()).optional(),
		/**
		 * Arbitrary mapping of strings to JSON values, for extension data not covered
		 * by the standard fields.
		 */
		meta: z.record(z.string(), z.unknown()).optional(),
		type: z.literal("essay"),
		/**
		 * The kind of editor shown to the student. `text` is a formatted (rich text)
		 * editor, `plain` a plain text box, and `code` a code editor, which is
		 * normally paired with `highlight`. Defaults to `"text"` when omitted.
		 */
		input: z.enum(["code", "text", "plain"]).optional(),
		/**
		 * Programming language used for syntax highlighting and, where supported,
		 * validation. Only applicable when `input` is `code`; it is ignored (and the
		 * linter warns) for any other input.
		 */
		highlight: z.string().min(1).optional(),
		/**
		 * A model answer. It guides the instructor while grading and MAY be shown to
		 * students as feedback afterwards.
		 */
		answerKey: z.string().min(1).regex(/\S/).optional(),
	})
	.strict();
export type Essay = z.infer<typeof EssaySchema>;

/**
 * A reference to a question defined outside this exam, by its id. Resolving the
 * reference is the host system's job; a document that merely fails to resolve
 * is still well-formed.
 */
export const ExamIncludeSchema = z
	.object({
		/** The id of the question to pull in. */
		include: z.string().regex(/^.*(\/?([a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*))+$/),
	})
	.strict();
export type ExamInclude = z.infer<typeof ExamIncludeSchema>;

/** A single option in a multiple-choice question. */
export const MultipleChoiceChoiceSchema = z
	.object({
		/** Unique url-friendly identifier for the choice. */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/** A textual display for the choice. */
		text: z.string().min(1),
		/**
		 * Numeric grade associated with the choice, on a scale from -1 to 1. 1 is
		 * considered correct and 0 incorrect. The instructor may omit this for
		 * incorrect choices, or set negative values as penalties for selecting a wrong
		 * choice. A question never clamps its own score -- whether a negative value
		 * survives into the exam total is decided entirely by the exam's `penalty`
		 * policy (see schema/exam.yaml), never here. A value outside [-1, 1] is a
		 * malformed question, not a clamped grade.
		 */
		score: z.number().min(-1).max(1).optional(),
		/**
		 * Feedback text shown to students that selected this choice. Usually explains
		 * why the choice is wrong (or right).
		 */
		feedback: z.string().optional(),
		/** Optional comment for the instructor. Do not shown to students. */
		comment: z.string().optional(),
	})
	.strict();
export type MultipleChoiceChoice = z.infer<typeof MultipleChoiceChoiceSchema>;

/**
 * A question where the student must select exactly one choice out of a list of
 * options. Extends the common question-base schema with a `choices` field.
 */
export const MultipleChoiceSchema = z
	.object({
		/**
		 * Url-friendly identifier for the question. Used to reference the question
		 * from exams, results, and cross-links. When omitted, an id may be derived
		 * from the question's position or title.
		 */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/**
		 * A universally unique identifier (UUID) for the question. Used to reference
		 * the question from exams, results, and cross-links. When omitted, a UUID may
		 * be generated automatically. Must be a valid UUID,
		 * `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` where `M` is the version and `N` is
		 * the variant.
		 */
		uuid: z
			.string()
			.regex(
				/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
			)
			.optional(),
		/**
		 * Human readable title, e.g. shown in question listings, tables of contents,
		 * or instructor-facing question banks.
		 */
		title: z.string().min(1).optional(),
		/** The name of the author or authors. Just for reference. */
		author: z.string().min(1).optional(),
		/**
		 * The main command shown to the students (e.g. "Select all correct answers",
		 * "Write a program that..."). This is the sentence that tells the student what
		 * to do and is always shown to them.
		 */
		stem: z.string().min(1),
		/**
		 * One or more paragraphs of context shown before the stem. May contain
		 * Markdown markup.
		 */
		preamble: z.string().optional(),
		/**
		 * One or more paragraphs of text shown after the question body (e.g. after the
		 * list of choices). May contain Markdown markup.
		 */
		epilogue: z.string().optional(),
		/**
		 * Free-form text shown only to instructors, never to students. Used to explain
		 * the intent of the question, grading rationale, formatting decisions, etc.
		 */
		comment: z.string().optional(),
		/**
		 * The language the question is written in, as an IETF BCP 47 language tag. BCP
		 * 47 is too involved to express as a JSON Schema `pattern`, so well-formedness
		 * is left to the implementation -- see the `malformed-locale` check in
		 * mdq.linter.
		 */
		locale: z.string().optional(),
		/** Arbitrary set of strings associated with the question. */
		tags: z.array(z.string()).optional(),
		/**
		 * Arbitrary mapping of strings to JSON values, for extension data not covered
		 * by the standard fields.
		 */
		meta: z.record(z.string(), z.unknown()).optional(),
		type: z.literal("multiple-choice"),
		/** The list of choices presented to the student. */
		choices: z.array(MultipleChoiceChoiceSchema).min(2),
		/**
		 * If true, the choices are safe to shuffle. If false, they should never be
		 * shuffled and if ommited, use the system is free to choose.
		 */
		shuffle: z.boolean().optional(),
	})
	.strict();
export type MultipleChoice = z.infer<typeof MultipleChoiceSchema>;

/** A single option in a multiple-selection question. */
export const MultipleSelectionChoiceSchema = z
	.object({
		/** Unique url-friendly identifier for the choice. */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/** A textual display for the choice. */
		text: z.string().min(1),
		/**
		 * Whether this choice should be selected in a correct answer. If omitted, it
		 * is interpreted as false (i.e. the choice should not be selected). Defaults
		 * to `false` when omitted.
		 */
		correct: z.boolean().optional(),
		/**
		 * Feedback text shown to students that judged this choice wrongly -- either by
		 * ticking one that should not be ticked, or by leaving unticked one that
		 * should be. Usually explains why the choice belongs in the answer or does
		 * not. Unlike multiple-choice, a correctly judged choice never shows it.
		 */
		feedback: z.string().optional(),
		/** Optional comment for the instructor. Do not show to students. */
		comment: z.string().optional(),
	})
	.strict();
export type MultipleSelectionChoice = z.infer<
	typeof MultipleSelectionChoiceSchema
>;

/**
 * A question where the student must select all choices they believe are
 * correct, out of a list of options (zero, one, or many may be correct).
 * Extends the common question-base schema with a `choices` field.
 */
export const MultipleSelectionSchema = z
	.object({
		/**
		 * Url-friendly identifier for the question. Used to reference the question
		 * from exams, results, and cross-links. When omitted, an id may be derived
		 * from the question's position or title.
		 */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/**
		 * A universally unique identifier (UUID) for the question. Used to reference
		 * the question from exams, results, and cross-links. When omitted, a UUID may
		 * be generated automatically. Must be a valid UUID,
		 * `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` where `M` is the version and `N` is
		 * the variant.
		 */
		uuid: z
			.string()
			.regex(
				/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
			)
			.optional(),
		/**
		 * Human readable title, e.g. shown in question listings, tables of contents,
		 * or instructor-facing question banks.
		 */
		title: z.string().min(1).optional(),
		/** The name of the author or authors. Just for reference. */
		author: z.string().min(1).optional(),
		/**
		 * The main command shown to the students (e.g. "Select all correct answers",
		 * "Write a program that..."). This is the sentence that tells the student what
		 * to do and is always shown to them.
		 */
		stem: z.string().min(1),
		/**
		 * One or more paragraphs of context shown before the stem. May contain
		 * Markdown markup.
		 */
		preamble: z.string().optional(),
		/**
		 * One or more paragraphs of text shown after the question body (e.g. after the
		 * list of choices). May contain Markdown markup.
		 */
		epilogue: z.string().optional(),
		/**
		 * Free-form text shown only to instructors, never to students. Used to explain
		 * the intent of the question, grading rationale, formatting decisions, etc.
		 */
		comment: z.string().optional(),
		/**
		 * The language the question is written in, as an IETF BCP 47 language tag. BCP
		 * 47 is too involved to express as a JSON Schema `pattern`, so well-formedness
		 * is left to the implementation -- see the `malformed-locale` check in
		 * mdq.linter.
		 */
		locale: z.string().optional(),
		/** Arbitrary set of strings associated with the question. */
		tags: z.array(z.string()).optional(),
		/**
		 * Arbitrary mapping of strings to JSON values, for extension data not covered
		 * by the standard fields.
		 */
		meta: z.record(z.string(), z.unknown()).optional(),
		type: z.literal("multiple-selection"),
		/** The list of choices presented to the student. */
		choices: z.array(MultipleSelectionChoiceSchema).min(2),
		/**
		 * If true, the choices are safe to shuffle. If false, they should never be
		 * shuffled and if ommited, use the system is free to choose.
		 */
		shuffle: z.boolean().optional(),
	})
	.strict();
export type MultipleSelection = z.infer<typeof MultipleSelectionSchema>;

/** A single statement in a true/false question. */
export const TrueFalseChoiceSchema = z
	.object({
		/** Unique url-friendly identifier for the choice. */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/** A textual display for the statement. */
		text: z.string().min(1),
		/**
		 * Whether the statement is true. If omitted, it is interpreted as false (i.e.
		 * the statement is false). Defaults to `false` when omitted.
		 */
		correct: z.boolean().optional(),
		/**
		 * The single letter written between the brackets in the source document (`T`,
		 * `F`, `V`, ...). Preserved verbatim: `answer` carries the meaning, but the
		 * letter itself is needed to warn about PROVISIONAL letters and locale
		 * mismatches, and to round-trip the document unchanged.
		 */
		marker: z.string().min(1).max(1).optional(),
		/**
		 * Feedback text shown to students that judged this statement incorrectly or
		 * left it unjudged. Usually explains why the statement is true or false.
		 */
		feedback: z.string().optional(),
		/** Optional comment for the instructor. Do not show to students. */
		comment: z.string().optional(),
	})
	.strict();
export type TrueFalseChoice = z.infer<typeof TrueFalseChoiceSchema>;

/**
 * A question where the student must judge each statement in a list as true or
 * false. Extends the common question-base schema with a `choices` field, where
 * each choice represents one statement to be judged.
 */
export const TrueFalseSchema = z
	.object({
		/**
		 * Url-friendly identifier for the question. Used to reference the question
		 * from exams, results, and cross-links. When omitted, an id may be derived
		 * from the question's position or title.
		 */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/**
		 * A universally unique identifier (UUID) for the question. Used to reference
		 * the question from exams, results, and cross-links. When omitted, a UUID may
		 * be generated automatically. Must be a valid UUID,
		 * `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` where `M` is the version and `N` is
		 * the variant.
		 */
		uuid: z
			.string()
			.regex(
				/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
			)
			.optional(),
		/**
		 * Human readable title, e.g. shown in question listings, tables of contents,
		 * or instructor-facing question banks.
		 */
		title: z.string().min(1).optional(),
		/** The name of the author or authors. Just for reference. */
		author: z.string().min(1).optional(),
		/**
		 * The main command shown to the students (e.g. "Select all correct answers",
		 * "Write a program that..."). This is the sentence that tells the student what
		 * to do and is always shown to them.
		 */
		stem: z.string().min(1),
		/**
		 * One or more paragraphs of context shown before the stem. May contain
		 * Markdown markup.
		 */
		preamble: z.string().optional(),
		/**
		 * One or more paragraphs of text shown after the question body (e.g. after the
		 * list of choices). May contain Markdown markup.
		 */
		epilogue: z.string().optional(),
		/**
		 * Free-form text shown only to instructors, never to students. Used to explain
		 * the intent of the question, grading rationale, formatting decisions, etc.
		 */
		comment: z.string().optional(),
		/**
		 * The language the question is written in, as an IETF BCP 47 language tag. BCP
		 * 47 is too involved to express as a JSON Schema `pattern`, so well-formedness
		 * is left to the implementation -- see the `malformed-locale` check in
		 * mdq.linter.
		 */
		locale: z.string().optional(),
		/** Arbitrary set of strings associated with the question. */
		tags: z.array(z.string()).optional(),
		/**
		 * Arbitrary mapping of strings to JSON values, for extension data not covered
		 * by the standard fields.
		 */
		meta: z.record(z.string(), z.unknown()).optional(),
		type: z.literal("true-false"),
		/**
		 * The list of statements presented to the student, each to be judged as true
		 * or false.
		 */
		choices: z.array(TrueFalseChoiceSchema).min(2),
		/**
		 * If true, the statements are safe to shuffle. If false, they should never be
		 * shuffled, and if omitted the system is free to choose.
		 */
		shuffle: z.boolean().optional(),
	})
	.strict();
export type TrueFalse = z.infer<typeof TrueFalseSchema>;

/**
 * Acceptable margin of error around the expected answer. Both fields are
 * optional; when both are given, a submitted value is accepted if it satisfies
 * either one.
 */
export const NumericToleranceSchema = z
	.object({
		/**
		 * Maximum allowed absolute difference between the submitted value and the
		 * answer, i.e. |submitted - answer| <= absolute.
		 */
		absolute: z.number().min(0).optional(),
		/**
		 * Maximum allowed relative difference between the submitted value and the
		 * answer, expressed as a fraction (e.g. 0.05 for 5%), i.e. |submitted -
		 * answer| / |answer| <= relative.
		 */
		relative: z.number().min(0).optional(),
	})
	.strict();
export type NumericTolerance = z.infer<typeof NumericToleranceSchema>;

/**
 * A question where the student must enter a numeric value, graded against an
 * expected answer within an optional tolerance. Extends the common
 * question-base schema with `answer` and `tolerance` fields.
 */
export const NumericSchema = z
	.object({
		/**
		 * Url-friendly identifier for the question. Used to reference the question
		 * from exams, results, and cross-links. When omitted, an id may be derived
		 * from the question's position or title.
		 */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/**
		 * A universally unique identifier (UUID) for the question. Used to reference
		 * the question from exams, results, and cross-links. When omitted, a UUID may
		 * be generated automatically. Must be a valid UUID,
		 * `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` where `M` is the version and `N` is
		 * the variant.
		 */
		uuid: z
			.string()
			.regex(
				/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
			)
			.optional(),
		/**
		 * Human readable title, e.g. shown in question listings, tables of contents,
		 * or instructor-facing question banks.
		 */
		title: z.string().min(1).optional(),
		/** The name of the author or authors. Just for reference. */
		author: z.string().min(1).optional(),
		/**
		 * The main command shown to the students (e.g. "Select all correct answers",
		 * "Write a program that..."). This is the sentence that tells the student what
		 * to do and is always shown to them.
		 */
		stem: z.string().min(1),
		/**
		 * One or more paragraphs of context shown before the stem. May contain
		 * Markdown markup.
		 */
		preamble: z.string().optional(),
		/**
		 * One or more paragraphs of text shown after the question body (e.g. after the
		 * list of choices). May contain Markdown markup.
		 */
		epilogue: z.string().optional(),
		/**
		 * Free-form text shown only to instructors, never to students. Used to explain
		 * the intent of the question, grading rationale, formatting decisions, etc.
		 */
		comment: z.string().optional(),
		/**
		 * The language the question is written in, as an IETF BCP 47 language tag. BCP
		 * 47 is too involved to express as a JSON Schema `pattern`, so well-formedness
		 * is left to the implementation -- see the `malformed-locale` check in
		 * mdq.linter.
		 */
		locale: z.string().optional(),
		/** Arbitrary set of strings associated with the question. */
		tags: z.array(z.string()).optional(),
		/**
		 * Arbitrary mapping of strings to JSON values, for extension data not covered
		 * by the standard fields.
		 */
		meta: z.record(z.string(), z.unknown()).optional(),
		type: z.literal("numeric"),
		/** The expected correct numeric value. */
		answer: z.number(),
		/** The unit (e.g., kg, m, lm, etc) of the expected answer. */
		unit: z
			.string()
			.regex(/^[\w.-_]+$/)
			.optional(),
		/** The domain/kind of number for the response. */
		domain: z.enum(["integer", "decimal", "fraction"]).optional(),
		/**
		 * The number of decimal places used in the decimal value representation. This
		 * value is ignored if domain is 'integer' or 'fraction'.
		 */
		decimalPlaces: z.int().min(0).optional(),
		tolerance: NumericToleranceSchema.optional(),
	})
	.strict();
export type Numeric = z.infer<typeof NumericSchema>;

/**
 * A question answered with a short piece of free text, graded by comparing the
 * response against a list of accepted answers or against a regular expression.
 * Extends the common question-base schema.
 */
export const ShortAnswerSchema = z
	.object({
		/**
		 * Url-friendly identifier for the question. Used to reference the question
		 * from exams, results, and cross-links. When omitted, an id may be derived
		 * from the question's position or title.
		 */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/**
		 * A universally unique identifier (UUID) for the question. Used to reference
		 * the question from exams, results, and cross-links. When omitted, a UUID may
		 * be generated automatically. Must be a valid UUID,
		 * `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` where `M` is the version and `N` is
		 * the variant.
		 */
		uuid: z
			.string()
			.regex(
				/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
			)
			.optional(),
		/**
		 * Human readable title, e.g. shown in question listings, tables of contents,
		 * or instructor-facing question banks.
		 */
		title: z.string().min(1).optional(),
		/** The name of the author or authors. Just for reference. */
		author: z.string().min(1).optional(),
		/**
		 * The main command shown to the students (e.g. "Select all correct answers",
		 * "Write a program that..."). This is the sentence that tells the student what
		 * to do and is always shown to them.
		 */
		stem: z.string().min(1),
		/**
		 * One or more paragraphs of context shown before the stem. May contain
		 * Markdown markup.
		 */
		preamble: z.string().optional(),
		/**
		 * One or more paragraphs of text shown after the question body (e.g. after the
		 * list of choices). May contain Markdown markup.
		 */
		epilogue: z.string().optional(),
		/**
		 * Free-form text shown only to instructors, never to students. Used to explain
		 * the intent of the question, grading rationale, formatting decisions, etc.
		 */
		comment: z.string().optional(),
		/**
		 * The language the question is written in, as an IETF BCP 47 language tag. BCP
		 * 47 is too involved to express as a JSON Schema `pattern`, so well-formedness
		 * is left to the implementation -- see the `malformed-locale` check in
		 * mdq.linter.
		 */
		locale: z.string().optional(),
		/** Arbitrary set of strings associated with the question. */
		tags: z.array(z.string()).optional(),
		/**
		 * Arbitrary mapping of strings to JSON values, for extension data not covered
		 * by the standard fields.
		 */
		meta: z.record(z.string(), z.unknown()).optional(),
		type: z.literal("short-answer"),
		/**
		 * The list of accepted responses; a response is correct if it matches any
		 * entry, after the normalization implied by `exact`. This is where the body's
		 * answer text is stored -- either the single string written after
		 * `[short-answer]:`, or the unordered list written below it.
		 */
		oneOf: z.array(z.string().min(1)).min(1).optional(),
		/**
		 * A regular expression matching every correct response. Matching is a *full
		 * match*, so leading `^` and trailing `$` are redundant. Set from the
		 * frontmatter, or from a body whose answer text is delimited by `/`; the
		 * frontmatter wins.
		 */
		regex: z.string().min(1).optional(),
		/**
		 * If true, compare responses verbatim. If false (the default), comparison
		 * ignores case, normalizes unicode letters, collapses runs of whitespace into
		 * a single space, and strips leading and trailing whitespace. Defaults to
		 * `false` when omitted.
		 */
		exact: z.boolean().optional(),
		/**
		 * If true, the question has no answer key and requires manual grading.
		 * Inferred when the body declares no answer text. Defaults to `false` when
		 * omitted.
		 */
		openEnded: z.boolean().optional(),
	})
	.strict();
export type ShortAnswer = z.infer<typeof ShortAnswerSchema>;

/**
 * Url-friendly identifier for the blank, matching the `[^id]` marker used in
 * the stem. MUST be unique within the question.
 */
export const FillInBlankIdSchema = z
	.string()
	.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/);
export type FillInBlankId = z.infer<typeof FillInBlankIdSchema>;

/**
 * A blank the student answers by picking one of a list of choices, graded
 * exactly like a multiple-choice question.
 */
export const FillInChoiceBlankSchema = z
	.object({
		id: FillInBlankIdSchema,
		type: z.literal("multiple-choice"),
		/** The list of choices presented for this blank. */
		choices: z.array(MultipleChoiceChoiceSchema).min(2),
	})
	.strict();
export type FillInChoiceBlank = z.infer<typeof FillInChoiceBlankSchema>;

/**
 * A blank the student answers by typing a short piece of text, graded exactly
 * like a short-answer question.
 */
export const FillInShortAnswerBlankSchema = z
	.object({
		id: FillInBlankIdSchema,
		type: z.literal("short-answer"),
		/**
		 * The list of accepted responses; a response is correct if it matches any
		 * entry, after the normalization implied by `exact`.
		 */
		oneOf: z.array(z.string().min(1)).min(1).optional(),
		/**
		 * A regular expression matching every correct response, applied as a full
		 * match. Takes precedence over `oneOf`.
		 */
		regex: z.string().min(1).optional(),
		/**
		 * If true, compare responses verbatim; if false (the default), normalize case,
		 * unicode letters, and whitespace first. Defaults to `false` when omitted.
		 */
		exact: z.boolean().optional(),
	})
	.strict();
export type FillInShortAnswerBlank = z.infer<
	typeof FillInShortAnswerBlankSchema
>;

/**
 * A blank the student answers with a number, graded exactly like a numeric
 * question.
 */
export const FillInNumericBlankSchema = z
	.object({
		id: FillInBlankIdSchema,
		type: z.literal("numeric"),
		/** The expected correct numeric value. */
		answer: z.number(),
		/** The unit (e.g., kg, m, lm, etc) of the expected answer. */
		unit: z
			.string()
			.regex(/^[\w.-]+$/)
			.optional(),
		/** The domain/kind of number for the response. */
		domain: z.enum(["integer", "decimal", "fraction"]).optional(),
		/**
		 * The number of decimal places used in the decimal value representation.
		 * Ignored if domain is 'integer' or 'fraction'.
		 */
		decimalPlaces: z.int().min(0).optional(),
		tolerance: NumericToleranceSchema.optional(),
	})
	.strict();
export type FillInNumericBlank = z.infer<typeof FillInNumericBlankSchema>;

/**
 * A single blank. `type` discriminates the three kinds; it is required here
 * even though the surface syntax may leave it implicit (`[^capital]:` infers
 * its kind from the definition that follows, while `[^size/numeric]:` states
 * it).
 */
export const FillInBlankSchema = z.discriminatedUnion("type", [
	FillInChoiceBlankSchema,
	FillInShortAnswerBlankSchema,
	FillInNumericBlankSchema,
]);
export type FillInBlank = z.infer<typeof FillInBlankSchema>;

/**
 * A question whose stem contains one or more named blanks, each answered in
 * place by the student. Extends the common question-base schema with a `blanks`
 * field. Every blank is itself a small graded question -- a set of choices, a
 * short answer, or a numeric value -- referenced from the stem by its id, as in
 * `The capital of Brazil is [^capital].`
 */
export const FillInSchema = z
	.object({
		/**
		 * Url-friendly identifier for the question. Used to reference the question
		 * from exams, results, and cross-links. When omitted, an id may be derived
		 * from the question's position or title.
		 */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/**
		 * A universally unique identifier (UUID) for the question. Used to reference
		 * the question from exams, results, and cross-links. When omitted, a UUID may
		 * be generated automatically. Must be a valid UUID,
		 * `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` where `M` is the version and `N` is
		 * the variant.
		 */
		uuid: z
			.string()
			.regex(
				/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
			)
			.optional(),
		/**
		 * Human readable title, e.g. shown in question listings, tables of contents,
		 * or instructor-facing question banks.
		 */
		title: z.string().min(1).optional(),
		/** The name of the author or authors. Just for reference. */
		author: z.string().min(1).optional(),
		/**
		 * The main command shown to the students (e.g. "Select all correct answers",
		 * "Write a program that..."). This is the sentence that tells the student what
		 * to do and is always shown to them.
		 */
		stem: z.string().min(1),
		/**
		 * One or more paragraphs of context shown before the stem. May contain
		 * Markdown markup.
		 */
		preamble: z.string().optional(),
		/**
		 * One or more paragraphs of text shown after the question body (e.g. after the
		 * list of choices). May contain Markdown markup.
		 */
		epilogue: z.string().optional(),
		/**
		 * Free-form text shown only to instructors, never to students. Used to explain
		 * the intent of the question, grading rationale, formatting decisions, etc.
		 */
		comment: z.string().optional(),
		/**
		 * The language the question is written in, as an IETF BCP 47 language tag. BCP
		 * 47 is too involved to express as a JSON Schema `pattern`, so well-formedness
		 * is left to the implementation -- see the `malformed-locale` check in
		 * mdq.linter.
		 */
		locale: z.string().optional(),
		/** Arbitrary set of strings associated with the question. */
		tags: z.array(z.string()).optional(),
		/**
		 * Arbitrary mapping of strings to JSON values, for extension data not covered
		 * by the standard fields.
		 */
		meta: z.record(z.string(), z.unknown()).optional(),
		type: z.literal("fill-in"),
		/**
		 * The blanks referenced by the stem, in the order their definitions appear in
		 * the document.
		 */
		blanks: z.array(FillInBlankSchema).min(1),
		/**
		 * If true, the choices of every choice-based blank are safe to shuffle. If
		 * false, they should never be shuffled, and if omitted the system is free to
		 * choose.
		 */
		shuffle: z.boolean().optional(),
	})
	.strict();
export type FillIn = z.infer<typeof FillInSchema>;

/**
 * One question block: either a question written inline, or a reference to one
 * stored elsewhere.
 */
export const ExamEntrySchema = z.union([
	ExamIncludeSchema,
	MultipleChoiceSchema,
	MultipleSelectionSchema,
	TrueFalseSchema,
	EssaySchema,
	NumericSchema,
	ShortAnswerSchema,
	FillInSchema,
]);
export type ExamEntry = z.infer<typeof ExamEntrySchema>;

/**
 * A set of questions gathered for assessment. An exam is recognized by its H1
 * title, which a question document can never carry. Each entry in `questions`
 * is either a complete question document or an `include` referring to one that
 * lives elsewhere.
 */
export const ExamSchema = z
	.object({
		/**
		 * Redundant in practice -- an exam is recognized by its H1 title -- but
		 * accepted so a document can state its kind explicitly.
		 */
		type: z.literal("exam").optional(),
		/**
		 * Url-friendly slug identifying the exam, written either in the H1 (`# [slug]
		 * Title`) or in the frontmatter. A number written in the frontmatter is read
		 * as its decimal string form.
		 */
		id: z
			.string()
			.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
			.optional(),
		/** Universally unique identifier for the exam. */
		uuid: z
			.string()
			.regex(
				/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
			)
			.optional(),
		/**
		 * Human readable title, normally taken from the H1 heading. When the
		 * frontmatter also sets it, the frontmatter wins.
		 */
		title: z.string().min(1).optional(),
		/** The course code the exam belongs to. */
		course: z.string().min(1).optional(),
		/** The exam author. Inherited by any question that does not name one. */
		author: z.string().min(1).optional(),
		/**
		 * The language the exam is written in, as an IETF BCP 47 language tag.
		 * Inherited by any question that does not set one. Well-formedness is left to
		 * the implementation -- see mdq.linter.
		 */
		locale: z.string().optional(),
		/**
		 * The paragraphs between the title and the first question, shown to the
		 * student before the assessment begins. May contain Markdown.
		 */
		instructions: z.string().optional(),
		/**
		 * Arbitrary set of strings associated with the exam. Unlike `locale` and
		 * `author`, tags are NOT inherited by the questions.
		 */
		tags: z.array(z.string()).optional(),
		/**
		 * Arbitrary mapping of strings to JSON values, for extension data not covered
		 * by the standard fields.
		 */
		meta: z.record(z.string(), z.unknown()).optional(),
		/**
		 * The exam's policy for whether a negative question score survives. Questions
		 * never clamp their own score -- this is the only place clamping happens.
		 * `none` floors each question score at 0 before weighting it into the total.
		 * `capped` keeps the full, possibly negative, question values but floors the
		 * exam total at 0. `full` floors nothing, at either level. Defaults to
		 * `"none"` when omitted.
		 */
		penalty: z.enum(["none", "capped", "full"]).optional(),
		/**
		 * The questions, in the order their blocks appear in the document. An entry is
		 * either a full question document or an `include`.
		 */
		questions: z.array(ExamEntrySchema),
	})
	.strict();
export type Exam = z.infer<typeof ExamSchema>;

/**
 * Common properties shared by every MDQ question type. Question-type schemas
 * (multiple-choice, multiple-selection, true-false, numeric, short-answer,
 * fill-in, essay) extend this schema, typically via `allOf` + `$ref`, and add
 * their own `type`-specific fields (e.g. `choices`).
 */
export const QuestionBaseSchema = z.object({
	/**
	 * Url-friendly identifier for the question. Used to reference the question
	 * from exams, results, and cross-links. When omitted, an id may be derived
	 * from the question's position or title.
	 */
	id: z
		.string()
		.regex(/^[a-zA-Z0-9]+(?:[-_][a-zA-Z0-9]+)*$/)
		.optional(),
	/**
	 * A universally unique identifier (UUID) for the question. Used to reference
	 * the question from exams, results, and cross-links. When omitted, a UUID may
	 * be generated automatically. Must be a valid UUID,
	 * `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` where `M` is the version and `N` is
	 * the variant.
	 */
	uuid: z
		.string()
		.regex(
			/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/,
		)
		.optional(),
	/**
	 * Human readable title, e.g. shown in question listings, tables of contents,
	 * or instructor-facing question banks.
	 */
	title: z.string().min(1).optional(),
	/** The name of the author or authors. Just for reference. */
	author: z.string().min(1).optional(),
	/**
	 * The main command shown to the students (e.g. "Select all correct answers",
	 * "Write a program that..."). This is the sentence that tells the student what
	 * to do and is always shown to them.
	 */
	stem: z.string().min(1),
	/**
	 * One or more paragraphs of context shown before the stem. May contain
	 * Markdown markup.
	 */
	preamble: z.string().optional(),
	/**
	 * One or more paragraphs of text shown after the question body (e.g. after the
	 * list of choices). May contain Markdown markup.
	 */
	epilogue: z.string().optional(),
	/**
	 * Free-form text shown only to instructors, never to students. Used to explain
	 * the intent of the question, grading rationale, formatting decisions, etc.
	 */
	comment: z.string().optional(),
	/**
	 * The language the question is written in, as an IETF BCP 47 language tag. BCP
	 * 47 is too involved to express as a JSON Schema `pattern`, so well-formedness
	 * is left to the implementation -- see the `malformed-locale` check in
	 * mdq.linter.
	 */
	locale: z.string().optional(),
	/** Arbitrary set of strings associated with the question. */
	tags: z.array(z.string()).optional(),
	/**
	 * Arbitrary mapping of strings to JSON values, for extension data not covered
	 * by the standard fields.
	 */
	meta: z.record(z.string(), z.unknown()).optional(),
});
export type QuestionBase = z.infer<typeof QuestionBaseSchema>;

/**
 * Any single MDQ question document: one of the seven question types,
 * discriminated by `type`.
 */
export const QuestionSchema = z.discriminatedUnion("type", [
	MultipleChoiceSchema,
	MultipleSelectionSchema,
	TrueFalseSchema,
	EssaySchema,
	NumericSchema,
	ShortAnswerSchema,
	FillInSchema,
]);
export type Question = z.infer<typeof QuestionSchema>;

/** Any MDQ document: an exam, or one of the seven question types. */
export const MdqDocumentSchema = z.union([QuestionSchema, ExamSchema]);
export type MdqDocument = z.infer<typeof MdqDocumentSchema>;
