"""
Auto generated data models.

All files in this directory are generated by the `datamodel-code-generator` tool
from the JSON schema files in the `schema-defs` directory. Please do not edit them
manually. Instead, either modify the JSON schema files and regenerate the models
using inv codegen command or modify the base classes in mdq.bases.
"""

from .base_question import BaseQuestion, MediaObject, Footnote, GradeRange, MediaType


__all__ = [
    "BaseQuestion",
    "Footnote",
    "GradeRange",
    "MediaObject",
    "MediaType",
]
